import { Profile } from './types';

// Liste de professions communes en Afrique de l'Ouest
export const AVAILABLE_PROFESSIONS = [
  'Développement Web',
  'Développement Mobile',
  'Design Graphique',
  'UI/UX Design',
  'Marketing Digital',
  'Consultation',
  'Data Science',
  'Gestion de Projet',
  'Photographie',
  'Vidéographie',
  'Rédaction',
  'Traduction',
  'Comptabilité',
  'Ressources Humaines',
  'Architecture',
  'Ingénierie',
  'Énergie Renouvelable',
  'Agriculture',
  'E-commerce',
  'Formation',
  'Coaching',
  'Santé & Bien-être',
  'Artisanat',
  'Mode & Textile',
  'Tourisme',
];

// Données mock pour 10 profils
export const MOCK_PROFILES: Profile[] = [
  {
    id: '1',
    name: 'ISMAEL CHRISTIAN DAOUDA ABASSI',
    title: 'Nexus Dev',
    city: 'Cotonou',
    country: 'Bénin',
    tags: ['Développement Web', 'Développement Mobile', 'Data Science', 'Gestion de Projet', 'Énergie Renouvelable'],
    rating: 4.8,
    reviewCount: 127,
    status: 'freelancer',
    tier: 'premium',
    whatsapp: '+22997123456',
    email: 'ismael@nexusdev.bj',
    isNewMember: false,
    joinDate: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'FATOUMATA DIALLO',
    title: 'Creative Studio Dakar',
    city: 'Dakar',
    country: 'Sénégal',
    tags: ['Design Graphique', 'UI/UX Design', 'Marketing Digital'],
    rating: 5.0,
    reviewCount: 89,
    status: 'agence-cabinet',
    tier: 'premium',
    whatsapp: '+221771234567',
    email: 'contact@creativestudio.sn',
    isNewMember: false,
    joinDate: new Date('2023-09-20'),
  },
  {
    id: '3',
    name: 'KWAME MENSAH',
    title: 'TechHub Accra',
    city: 'Accra',
    country: 'Ghana',
    tags: ['Développement Web', 'Formation', 'Consultation'],
    rating: 4.6,
    reviewCount: 203,
    status: 'entreprise',
    tier: 'premium',
    whatsapp: '+233241234567',
    email: 'info@techhub.gh',
    isNewMember: false,
    joinDate: new Date('2022-11-10'),
  },
  {
    id: '4',
    name: 'AMINATA TRAORÉ',
    title: 'Agence Baobab',
    city: 'Bamako',
    country: 'Mali',
    tags: ['Marketing Digital', 'Photographie', 'Rédaction'],
    rating: 4.9,
    reviewCount: 56,
    status: 'pme',
    tier: 'freemium',
    whatsapp: '+22376543210',
    email: 'aminata@baobab.ml',
    isNewMember: true,
    joinDate: new Date('2024-10-25'),
  },
  {
    id: '5',
    name: 'CHUKWUDI OKONKWO',
    title: 'Lagos Digital Solutions',
    city: 'Lagos',
    country: 'Nigeria',
    tags: ['E-commerce', 'Développement Web', 'Data Science'],
    rating: 4.7,
    reviewCount: 312,
    status: 'entreprise',
    tier: 'premium',
    whatsapp: '+2348012345678',
    email: 'info@lagosdigital.ng',
    isNewMember: false,
    joinDate: new Date('2021-03-12'),
  },
  {
    id: '6',
    name: 'ADJOUA KOFFI',
    title: 'Artisan Textile Abidjan',
    city: 'Abidjan',
    country: 'Côte d\'Ivoire',
    tags: ['Mode & Textile', 'Artisanat', 'Design Graphique'],
    rating: 4.5,
    reviewCount: 45,
    status: 'artisan',
    tier: 'free',
    whatsapp: '+2250701234567',
    email: 'adjoua.koffi@gmail.com',
    isNewMember: true,
    joinDate: new Date('2024-10-30'),
  },
  {
    id: '7',
    name: 'SEYNI COULIBALY',
    title: 'ONG Action Climat',
    city: 'Ouagadougou',
    country: 'Burkina Faso',
    tags: ['Énergie Renouvelable', 'Formation', 'Gestion de Projet'],
    rating: 4.8,
    reviewCount: 67,
    status: 'ong',
    tier: 'freemium',
    whatsapp: '+22670123456',
    email: 'contact@actionclimat.bf',
    isNewMember: false,
    joinDate: new Date('2023-06-15'),
  },
  {
    id: '8',
    name: 'EMMA AGBODJAN',
    title: 'Étudiante en Architecture',
    city: 'Lomé',
    country: 'Togo',
    tags: ['Architecture', 'Design Graphique'],
    rating: 4.3,
    reviewCount: 12,
    status: 'etudiant',
    tier: 'free',
    whatsapp: '+22890123456',
    email: 'emma.agbodjan@univ-lome.tg',
    isNewMember: true,
    joinDate: new Date('2024-11-01'),
  },
  {
    id: '9',
    name: 'MOUSSA BARRY',
    title: 'Consultant Marketing',
    city: 'Cotonou',
    country: 'Bénin',
    tags: ['Marketing Digital', 'Consultation', 'Formation'],
    rating: 4.9,
    reviewCount: 134,
    status: 'freelancer',
    tier: 'freemium',
    whatsapp: '+22997654321',
    email: 'moussa.barry@gmail.com',
    isNewMember: false,
    joinDate: new Date('2023-02-20'),
  },
  {
    id: '10',
    name: 'GRACE NDIAYE',
    title: 'Photographe Freelance',
    city: 'Dakar',
    country: 'Sénégal',
    tags: ['Photographie', 'Vidéographie', 'Marketing Digital'],
    rating: 5.0,
    reviewCount: 98,
    status: 'freelancer',
    tier: 'premium',
    whatsapp: '+221771234890',
    email: 'grace@gracephoto.sn',
    isNewMember: false,
    joinDate: new Date('2022-08-10'),
  },
];
